default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: leetcode_tracker_dev
  username: postgres
  password: 1234
  host: localhost

test:
  <<: *default
  database: leetcode_tracker_test
  username: postgres
  password: 1234
  host: localhost

production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>
